#!/bin/bash
# Digital Ocean Droplet Setup Script
# Run this script on a fresh Ubuntu 24.04 droplet
# Usage: bash setup-server.sh (must be downloaded first, not piped, due to interactive prompts)

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

echo ""
echo "========================================"
echo "  FastAPI Droplet Setup Script"
echo "  Digital Ocean - Ubuntu 24.04"
echo "========================================"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    log_error "Please run as root: sudo bash setup-server.sh"
    exit 1
fi

# Step 1: Update system
log_step "1/7 - Updating system packages..."
apt update && apt upgrade -y
log_info "System updated."

# Step 2: Install Docker
log_step "2/7 - Installing Docker..."
if command -v docker &> /dev/null; then
    log_info "Docker already installed."
else
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    log_info "Docker installed and started."
fi

# Step 3: Install Docker Compose plugin
log_step "3/7 - Installing Docker Compose plugin..."
apt install docker-compose-plugin -y
log_info "Docker Compose plugin installed."

# Step 4: Configure firewall
log_step "4/7 - Configuring firewall..."
ufw allow OpenSSH
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 8000/tcp
ufw --force enable
log_info "Firewall configured."

# Step 5: Clone repository
log_step "5/7 - Cloning repository..."
APP_DIR="/opt/fastapi"
if [ -d "$APP_DIR" ]; then
    log_warn "Directory $APP_DIR already exists. Pulling latest changes..."
    cd $APP_DIR
    git pull origin main
else
    cd /opt
    git clone https://github.com/prasadvenkat22/fastapi.git
    cd $APP_DIR
fi
log_info "Repository ready at $APP_DIR"

# Step 6: Setup deploy script
log_step "6/7 - Setting up deployment scripts..."
chmod +x deploy.sh
log_info "Deploy script ready."

# Step 7: Setup environment file
log_step "7/7 - Setting up environment configuration..."
if [ ! -f ".env.production.example" ]; then
    log_error ".env.production.example template not found!"
    exit 1
fi

echo ""
echo "========================================"
echo "  Environment Configuration"
echo "========================================"
echo ""

# Prompt for essential configuration
read -p "Enter PostgreSQL password: " -s DB_PASSWORD
echo ""
read -p "Enter pgAdmin password: " -s PGADMIN_PASSWORD
echo ""
read -p "Enter OpenAI API Key: " -s OPENAI_KEY
echo ""
read -p "Enter your domain (or press Enter for IP only): " DOMAIN

# Generate secure JWT secret
JWT_SECRET=$(openssl rand -hex 32)

# Get external IP
EXTERNAL_IP=$(curl -s ifconfig.me)

# Create production environment file with user values
# IMPORTANT: Docker Compose .env files must NOT have quotes around values
cat > .env.production << ENVEOF
# Production Environment Configuration
# Generated by setup-server.sh on $(date)
# IMPORTANT: Do NOT add quotes around values - Docker Compose treats them literally

# PostgreSQL Configuration
DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@pgdb:5432/postgres
DB_USER=postgres
DB_PASSWORD=${DB_PASSWORD}
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=postgres

# pgAdmin (only used with --profile debug)
PGADMIN_EMAIL=admin@admin.com
PGADMIN_PASSWORD=${PGADMIN_PASSWORD}
PGADMIN_DEFAULT_EMAIL=admin@admin.com
PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}

# MongoDB Configuration
MONGODB_URL=mongodb://mongo:27017
DB_NAME=TENANT

# Application Configuration
APP_PORT=5000
PORT=5000

# JWT/Auth Configuration
secret=${JWT_SECRET}
algorithm=HS256
ACCESS_TOKEN_EXPIRES_IN=15
REFRESH_TOKEN_EXPIRES_IN=60
JWT_ALGORITHM=RS256
CLIENT_ORIGIN=${DOMAIN:-http://${EXTERNAL_IP}}

# JWT Keys (using same keys from development - generate new ones for high security)
JWT_PRIVATE_KEY=LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlCT2dJQkFBSkJBSSs3QnZUS0FWdHVQYzEzbEFkVk94TlVmcWxzMm1SVmlQWlJyVFpjd3l4RVhVRGpNaFZuCi9KVHRsd3h2a281T0pBQ1k3dVE0T09wODdiM3NOU3ZNd2xNQ0F3RUFBUUpBYm5LaENOQ0dOSFZGaHJPQ0RCU0IKdmZ2ckRWUzVpZXAwd2h2SGlBUEdjeWV6bjd0U2RweUZ0NEU0QTNXT3VQOXhqenNjTFZyb1pzRmVMUWlqT1JhUwp3UUloQU84MWl2b21iVGhjRkltTFZPbU16Vk52TGxWTW02WE5iS3B4bGh4TlpUTmhBaUVBbWRISlpGM3haWFE0Cm15QnNCeEhLQ3JqOTF6bVFxU0E0bHUvT1ZNTDNSak1DSVFEbDJxOUdtN0lMbS85b0EyaCtXdnZabGxZUlJPR3oKT21lV2lEclR5MUxaUVFJZ2ZGYUlaUWxMU0tkWjJvdXF4MHdwOWVEejBEWklLVzVWaSt6czdMZHRDdUVDSUVGYwo3d21VZ3pPblpzbnU1clBsTDJjZldLTGhFbWwrUVFzOCtkMFBGdXlnCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
JWT_PUBLIC_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZ3d0RRWUpLb1pJaHZjTkFRRUJCUUFEU3dBd1NBSkJBSSs3QnZUS0FWdHVQYzEzbEFkVk94TlVmcWxzMm1SVgppUFpSclRaY3d5eEVYVURqTWhWbi9KVHRsd3h2a281T0pBQ1k3dVE0T09wODdiM3NOU3ZNd2xNQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==

# OpenAI API Key
OPENAI_API_KEY=${OPENAI_KEY}

# Production Settings
ENVIRONMENT=production
DEBUG=false
ENVEOF

log_info "Environment file created."

# Create .env symlink so base docker-compose.yml can resolve env_file: .env
ln -sf .env.production .env
log_info "Created .env symlink -> .env.production"

echo ""
echo "========================================"
echo "  Setup Complete!"
echo "========================================"
echo ""
log_info "Application directory: $APP_DIR"
log_info "Environment file: $APP_DIR/.env.production"
echo ""
echo "Next steps:"
echo "  1. cd $APP_DIR"
echo "  2. ./deploy.sh start"
echo "  3. ./deploy.sh health"
echo ""
echo "Access your application at:"
echo "  - FastAPI:   http://${EXTERNAL_IP}:8000/docs"
echo ""

# Ask if user wants to start now
read -p "Start the application now? (y/n): " START_NOW
if [[ "$START_NOW" =~ ^[Yy]$ ]]; then
    log_info "Starting application..."
    ./deploy.sh start
    echo ""
    log_info "Waiting for services to initialize..."
    sleep 10
    ./deploy.sh health
fi

echo ""
log_info "Setup complete!"
