"""add image_url to all entities

Revision ID: 955b7cd7708a
Revises: 
Create Date: 2026-04-06 01:01:13.618242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '955b7cd7708a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # documents is managed by GENAI/vector_stores.py via raw asyncpg (not an ORM
    # model), so it may not exist yet on a fresh database — drop it only if present.
    op.execute("DROP TABLE IF EXISTS documents")
    op.add_column('customers', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('devices', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('services', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_url')
    op.drop_column('services', 'image_url')
    op.drop_column('invoices', 'image_url')
    op.drop_column('devices', 'image_url')
    op.drop_column('customers', 'image_url')
    # Recreated without the vector-typed embedding column (unsupported by plain
    # SQLAlchemy DDL) — GENAI/vector_stores.py recreates it correctly with the
    # pgvector extension the next time it runs.
    op.execute("""
        CREATE TABLE IF NOT EXISTS documents (
            id TEXT PRIMARY KEY,
            text TEXT,
            metadata JSONB
        )
    """)
    # ### end Alembic commands ###
