"""add image_url to all entities

Revision ID: 955b7cd7708a
Revises: 
Create Date: 2026-04-06 01:01:13.618242

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '955b7cd7708a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # documents is managed by GENAI/vector_stores.py via raw asyncpg (not an ORM
    # model), so it may not exist yet on a fresh database — drop it only if present.
    op.execute("DROP TABLE IF EXISTS documents")
    # Guard each column add too: alembic runs before main.py's
    # Base.metadata.create_all() startup hook, so on a fresh database these tables
    # don't exist yet. The models already declare image_url natively, so
    # create_all() picks it up on its own — this only needs to backfill the
    # column on a database where the tables predate that model change.
    for table in ("customers", "devices", "invoices", "services", "users"):
        op.execute(f"ALTER TABLE IF EXISTS {table} ADD COLUMN IF NOT EXISTS image_url VARCHAR")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table in ("users", "services", "invoices", "devices", "customers"):
        op.execute(f"ALTER TABLE IF EXISTS {table} DROP COLUMN IF EXISTS image_url")
    # Recreated without the vector-typed embedding column (unsupported by plain
    # SQLAlchemy DDL) — GENAI/vector_stores.py recreates it correctly with the
    # pgvector extension the next time it runs.
    op.execute("""
        CREATE TABLE IF NOT EXISTS documents (
            id TEXT PRIMARY KEY,
            text TEXT,
            metadata JSONB
        )
    """)
    # ### end Alembic commands ###
